FROM onnxruntime-cuda-okitch-semseg:latest

ARG USER_ID
ARG GROUP_ID

RUN groupadd -g $GROUP_ID usergroup || true && \
    useradd -l -u $USER_ID -g usergroup user || true && \
    install -d -m 0755 -o user -g usergroup /home/user

USER user